trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript:   |
                      cd apps/templates
                      chmod +x automated-deployment.sh
                      ./automated-deployment.sh
    displayName: 'Deploy infrastructure'