name: Push from dockerhub to acr

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Build-push-docker:

    runs-on: ubuntu-latest

    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Azure login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Push images
          run:  |
                az acr login --name damwarregistry.azurecr.io
                docker pull damwar/node-sdk:latest
                docker tag damwar/node-sdk:latest damwarregistry.azurecr.io/sdks/node-sdk
                docker push damwarregistry.azurecr.io/sdks/node-sdk
                docker pull damwar/dotnet-sdk:latest
                docker tag damwar/dotnet-sdk:latest damwarregistry.azurecr.io/sdks/dotnet-sdk
                docker push damwarregistry.azurecr.io/sdks/dotnet-sdk
                
