# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: containerUrl
  value: https://mystorageaccount.blob.core.windows.net/container
- name: packageName
  value: package.zip

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript:   |
                      apt-get install zip -y
                      zip -r '${{ variables.packageName }}' code
                      templates/automated-deployment.sh
                      azcopy copy '${{ variables.packageName }}' '${{ variables.containerUrl }}/${{ variables.packageName }}'


  
