# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: containerUrl
  value: https://damwarstorage04.blob.core.windows.net/container
- name: packageName
  value: package.zip
- name: resourceGroup
  value: infrastructure-01
- name: functionAppName
  value: damwar-function-02

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript:   |
                      cd templates
                      chmod 755 automated-deployment.sh
                      ./automated-deployment.sh
    displayName: Deploy infrastructure
    
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript:   |
                      apt-get install zip -y
                      zip -r '${{ variables.packageName }}' code
                      az functionapp deployment source config-zip -g '${{ resourceGroup }}' -n '${{ functionAppName }}' --src '${{ variables.packageName }}'
    displayName: Upload code package


  
