trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
          cd templates
          chmod +x automated-deployment.sh
          ./automated-deployment.sh
  displayName: 'Deploy infrastructure'
