trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acr-damwarregistry'
    repository: 'restart-apps'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'