name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy from scripts
        run:  |
              az config set defaults.group=infrastructure-01
              cd azure-cli/session-07
              chmod 755 create-vnet-subnets.sh
              ./create-vnet-subnets.sh
              chmod 755 create-nsg.sh
              ./create-nsg.sh
