name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy from scripts
        run:  |
              az config set defaults.group=infrastructure-01
              cd azure-cli
              cd session-07
              chmod 755 script2.sh
              ./script2.sh
              chmod 755 script3.sh
              ./script3.sh
